import { createFileRoute, Link } from "@tanstack/react-router";
import { useState } from "react";
import { Archive, BarChart3, CalendarDays, ChevronDown, FileCheck2, MapPin, ArrowRight } from "lucide-react";
import { CompactFinalCTA } from "@/components/CompactFinalCTA";
import { HeroButton, PageHero, Section, SectionTitle } from "@/components/PageHero";
import { HatchedCircle, QuarterCircle, Triangle } from "@/components/Shapes";

export const Route = createFileRoute("/impacto-memoria")({ head:()=>({meta:[
 {title:"Impacto & Memória | Associação Maggu"},{name:"description",content:"Conheça marcos, memórias e evidências da trajetória da Associação Maggu."},{property:"og:title",content:"Impacto & Memória | Associação Maggu"},{property:"og:description",content:"Resultados e histórias da Associação Maggu caminham juntos."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"},
]}),component:ImpactoMemoria });
const indicators=[
 {label:"Anos de trajetória",status:"Referência cultural desde 1999",note:"Distinta da formalização jurídica em 2025."},
 {label:"Pessoas alcançadas",status:"Em consolidação",note:"Publicação após validação interna."},
 {label:"Atividades realizadas",status:"Em consolidação",note:"Organização por período e categoria."},
 {label:"Projetos ativos",status:"Estrutura preparada",note:"Atualização futura pela gestão de conteúdo."},
 {label:"Territórios e parcerias",status:"Em consolidação",note:"Somente dados documentados serão publicados."},
];
const timeline=[
 ["1999","Início da trajetória artística com a Companhia de Teatro Cortina."],["2001","A Paixão de Cristo amplia a presença cultural no território."],["2025","Formalização da Associação Sócio Cultural Maggu."],["2025","Teatro Escola Maggu certificado como Ponto de Cultura."],["2026","Fortalecimento da governança, Comissão ODS e consolidação do Ecossistema Maggu."],
];
const archiveTypes=["Fotografias","Cartazes","Vídeos","Programas","Publicações","Documentos"];
const evidenceTypes=["Certificados","Declarações","Registros","Matérias","Relatórios","Programas e publicações"];
function Filters({kind}:{kind:"acervo"|"evidencias"}){const [open,setOpen]=useState(false);return <div className="rounded-xl border border-brand-petrol/10 bg-background/70 p-3"><button type="button" onClick={()=>setOpen(v=>!v)} className="flex w-full items-center justify-between text-sm font-semibold md:hidden" aria-expanded={open}>Filtros <ChevronDown className={`size-4 transition ${open?"rotate-180":""}`}/></button><div className={`${open?"grid":"hidden"} mt-3 gap-3 sm:grid-cols-3 md:mt-0 md:grid`}>{(kind==="acervo"?["Ano","Iniciativa","Tipo de acervo"]:["Tipo","Iniciativa","Ano"]).map(label=><label key={label} className="text-xs font-semibold uppercase tracking-[.12em] text-brand-gray">{label}<select className="mt-1.5 h-10 w-full rounded-lg border border-brand-petrol/15 bg-background px-3 text-sm normal-case tracking-normal text-brand-ink"><option>Todos</option></select></label>)}</div></div>}
function EmptyState({text}:{text:string}){return <div className="mt-5 rounded-2xl border border-dashed border-brand-petrol/25 bg-background/50 px-6 py-10 text-center"><Archive className="mx-auto size-7 text-brand-cyan"/><p className="mx-auto mt-3 max-w-xl text-sm leading-relaxed text-brand-gray">{text}</p></div>}
function ImpactoMemoria(){return <>
 <PageHero eyebrow="Impacto & Memória" title="Impacto que pode ser visto, contado e lembrado." subtitle="Cada oficina, sessão, livro, encontro, apresentação ou formação só ganha sentido quando produz experiência, acesso, memória e possibilidade. Por isso, registramos resultados sem reduzir pessoas a números." image="https://images.unsplash.com/photo-1519683384663-1de1a1e3f6a7?auto=format&fit=crop&w=1920&q=80" accent="gold" brush="#08B9E6" decoration="frame"><HeroButton to="#memoria" tone="gold">Explorar memória</HeroButton><HeroButton to="#evidencias" tone="cyan">Ver evidências</HeroButton></PageHero>
 <Section className="relative overflow-hidden bg-background"><QuarterCircle corner="tr" color="#FFB400" className="absolute -right-2 -top-2 w-24 opacity-20"/><div className="container-x"><div className="mx-auto max-w-4xl text-center"><SectionTitle align="center" title="Resultados e histórias precisam caminhar juntos."/><p className="leading-relaxed text-brand-gray">Nesta página, indicadores quantitativos convivem com histórias, fotografias, documentos e evidências. Todo número publicado deverá indicar seu período de referência e origem.</p></div></div></Section>
 <Section className="overflow-hidden bg-brand-soft"><div className="container-x"><SectionTitle eyebrow="Indicadores" title="O que podemos acompanhar"/><div className="grid gap-4 sm:grid-cols-2 lg:grid-cols-5">{indicators.map((item,i)=><article key={item.label} className="rounded-2xl border border-brand-petrol/10 bg-background/75 p-5 shadow-sm"><BarChart3 className={`size-5 ${i===0?"text-brand-red":"text-brand-cyan"}`}/><h3 className="mt-5 text-base leading-snug">{item.label}</h3><p className="mt-3 text-sm font-semibold text-brand-petrol">{item.status}</p><p className="mt-1.5 text-xs leading-relaxed text-brand-gray">{item.note}</p></article>)}</div></div></Section>
 <Section id="memoria" className="relative overflow-hidden bg-background"><HatchedCircle size={160} color="#ED1C24" className="absolute -left-16 bottom-8 opacity-10"/><div className="container-x"><SectionTitle eyebrow="Memória Maggu" title="Registrar também é cuidar do que construímos."/><div className="max-w-4xl space-y-4 leading-relaxed text-brand-gray"><p>A Memória Maggu reúne fotografias, cartazes, vídeos, programas, publicações, produções e documentos que ajudam a contar uma trajetória construída por muitas pessoas.</p><p>Mais do que uma galeria, é um acervo vivo: preserva processos, reconhece participações e transforma documentação em patrimônio institucional e comunitário.</p></div><div className="mt-8"><Filters kind="acervo"/><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-6">{archiveTypes.map((type,i)=><div key={type} className="rounded-xl border border-brand-petrol/10 bg-brand-soft/50 p-4"><span className={`mb-3 block size-2 rotate-45 ${i%3===0?"bg-brand-red":i%3===1?"bg-brand-gold":"bg-brand-cyan"}`}/><p className="text-sm font-semibold">{type}</p></div>)}</div><EmptyState text="Os registros do acervo serão apresentados aqui conforme forem organizados e validados pela Associação."/></div></div></Section>
 <Section className="overflow-hidden bg-brand-soft"><div className="container-x"><SectionTitle align="center" title="Uma trajetória construída ao longo do tempo."/><ol className="relative mt-10 grid gap-4 md:grid-cols-5 md:gap-0"><span className="absolute left-[10%] right-[10%] top-4 hidden h-px bg-brand-petrol/20 md:block"/>{timeline.map(([year,text],i)=><li key={`${year}-${text}`} className="relative grid grid-cols-[auto_1fr] gap-4 md:block md:px-3 md:pt-10 md:text-center"><span className={`mt-1 size-3 rounded-full ring-4 ring-brand-soft md:absolute md:left-1/2 md:top-2 md:-translate-x-1/2 ${i%3===0?"bg-brand-red":i%3===1?"bg-brand-gold":"bg-brand-cyan"}`}/><div><p className="text-xl font-bold text-brand-red">{year}</p><p className="mt-2 text-sm leading-relaxed text-brand-gray">{text}</p></div></li>)}</ol></div></Section>
 <Section className="overflow-hidden bg-background"><div className="container-x"><SectionTitle eyebrow="Histórias" title="Nem todo impacto cabe em um número." text="Esta área está preparada para histórias e relatos relacionados às iniciativas, publicados somente após validação institucional."/><EmptyState text="Novas histórias serão reunidas aqui sem criar depoimentos ou informações não confirmadas."/></div></Section>
 <Section id="evidencias" className="relative overflow-hidden bg-brand-soft"><Triangle color="#FFB400" size={34} className="absolute right-[8%] top-10 opacity-40" rotate={22}/><div className="container-x"><SectionTitle eyebrow="Evidências" title="Documentos que ajudam a comprovar trajetórias e resultados." text="O Banco de Evidências reúne certificados, declarações, registros, matérias, relatórios, programas, publicações e outros documentos comprobatórios."/><div className="grid gap-4 md:grid-cols-2"><article className="rounded-2xl border border-brand-cyan/25 bg-background/75 p-6"><FileCheck2 className="size-5 text-brand-cyan"/><h3 className="mt-4 text-lg">Evidências</h3><p className="mt-2 text-sm leading-relaxed text-brand-gray">Comprovam trajetória, participação, execução e impacto.</p></article><article className="rounded-2xl border border-brand-gold/30 bg-background/75 p-6"><FileCheck2 className="size-5 text-brand-gold"/><h3 className="mt-4 text-lg">Transparência</h3><p className="mt-2 text-sm leading-relaxed text-brand-gray">Reúne governança, políticas e documentos institucionais.</p></article></div><div className="mt-6"><Filters kind="evidencias"/><div className="mt-4 grid grid-cols-2 gap-3 sm:grid-cols-3">{evidenceTypes.map(item=><div key={item} className="rounded-xl border border-brand-petrol/10 bg-background/60 p-4 text-sm font-semibold">{item}</div>)}</div><EmptyState text="Documentos aparecerão nesta área somente quando houver arquivos reais e autorização para visualização ou download."/></div></div></Section>
 <Section className="overflow-hidden bg-brand-petrol text-primary-foreground"><div className="container-x grid items-center gap-6 md:grid-cols-[auto_1fr_auto]"><span className="inline-flex size-14 items-center justify-center rounded-full bg-brand-cyan/15"><MapPin className="size-6 text-brand-cyan"/></span><div><h2 className="text-2xl text-primary-foreground">Impacto também tem território.</h2><p className="mt-2 leading-relaxed text-primary-foreground/80">Conheça melhor a relação da Associação Maggu com o Benedito Bentes e como essa presença atravessa projetos, memórias e experiências.</p></div><Link to="/quem-somos/territorio" className="inline-flex items-center gap-2 rounded-full bg-brand-gold px-5 py-3 text-sm font-semibold text-brand-petrol">Conheça o território <ArrowRight className="size-4"/></Link></div></Section>
 <Section className="bg-background"><div className="container-x"><nav aria-label="Conexões" className="flex flex-wrap justify-center gap-3"><Link to="/ecossistema" className="rounded-full border border-brand-petrol/20 px-5 py-2 text-sm font-semibold">Ecossistema</Link><Link to="/quem-somos/territorio" className="rounded-full border border-brand-petrol/20 px-5 py-2 text-sm font-semibold">Território</Link><Link to="/transparencia" className="rounded-full border border-brand-petrol/20 px-5 py-2 text-sm font-semibold">Transparência</Link></nav></div></Section>
 <CompactFinalCTA title="Conheça o que permanece depois de cada ação." text="Explore projetos, memórias, documentos e evidências da trajetória da Associação Maggu." primary={{label:"Explorar memória",href:"#memoria"}} secondary={{label:"Ver Transparência",to:"/transparencia"}} variant="continuity"/>
 </>}
