import { createFileRoute, Link } from "@tanstack/react-router";
import { CalendarDays, GraduationCap, HandHeart, Handshake, Sparkles, ArrowRight, CircleDollarSign, BookOpen, Package, Wrench, Building2, Megaphone } from "lucide-react";
import { CompactFinalCTA } from "@/components/CompactFinalCTA";
import { HeroButton, PageHero, Section, SectionTitle } from "@/components/PageHero";
import { ArcThick, HatchedCircle, QuarterCircle } from "@/components/Shapes";
import { Button } from "@/components/ui/button";

export const Route = createFileRoute("/participe")({ head:()=>({meta:[
 {title:"Participe | Associação Maggu"},{name:"description",content:"Conheça formas de participar, colaborar, apoiar ou construir uma parceria com a Associação Maggu."},{property:"og:title",content:"Participe | Associação Maggu"},{property:"og:description",content:"Há muitas formas de fazer parte do Ecossistema Maggu."},{property:"og:type",content:"website"},{name:"twitter:card",content:"summary_large_image"},
]}),component:Participe });
const paths=[
 {title:"Atividades",text:"Veja o que está acontecendo e encontre uma ação para participar.",cta:"Ver Agenda",to:"/agenda",icon:CalendarDays,accent:"bg-brand-red"},
 {title:"Formação",text:"Conheça cursos, oficinas e percursos formativos.",cta:"Ver formações",to:"/projetos",icon:GraduationCap,accent:"bg-brand-gold"},
 {title:"Colaboração",text:"Artistas, educadores, voluntários e outros colaboradores podem somar conhecimentos e experiências.",cta:"Quero colaborar",to:"#colaboracao",icon:Sparkles,accent:"bg-brand-cyan"},
 {title:"Parcerias",text:"Instituições, empresas e organizações podem construir ações, projetos e cooperações com a Associação.",cta:"Propor parceria",to:"#parcerias",icon:Handshake,accent:"bg-brand-orange"},
 {title:"Apoio",text:"Contribuições, materiais, livros, equipamentos, serviços e outras formas de apoio ajudam a manter iniciativas em movimento.",cta:"Quero apoiar",to:"#apoie",icon:HandHeart,accent:"bg-brand-lime"},
] as const;
const support=[{label:"Contribuição financeira",icon:CircleDollarSign},{label:"Materiais e equipamentos",icon:Package},{label:"Livros",icon:BookOpen},{label:"Serviços",icon:Wrench},{label:"Parceria institucional",icon:Building2},{label:"Patrocínio",icon:Megaphone}];
function Participe(){return <>
 <PageHero eyebrow="Participe" title="Há muitas formas de fazer parte." subtitle="O Ecossistema Maggu é feito de encontros. Você pode participar de uma atividade, iniciar uma formação, colaborar com uma ação, compartilhar conhecimento, apoiar uma iniciativa ou construir uma parceria." image="https://images.unsplash.com/photo-1517048676732-d65bc937f952?auto=format&fit=crop&w=1920&q=80" accent="gold" brush="#ED1C24" decoration="constellation"><HeroButton to="/agenda" tone="gold">Ver Agenda</HeroButton><HeroButton to="#caminhos" tone="cyan">Conheça os caminhos</HeroButton></PageHero>
 <Section id="caminhos" className="relative overflow-hidden bg-background"><HatchedCircle size={160} color="#08B9E6" className="absolute -right-16 top-10 opacity-10"/><div className="container-x"><SectionTitle align="center" eyebrow="Escolha como participar" title="Encontre a forma que combina com você."/><div className="grid gap-4 md:grid-cols-2 lg:grid-cols-6">{paths.map(({title,text,cta,to,icon:Icon,accent},i)=><article key={title} className={`group relative flex min-h-64 flex-col overflow-hidden rounded-2xl border border-brand-petrol/10 bg-brand-soft/45 p-6 shadow-sm transition hover:-translate-y-1 hover:border-brand-petrol/20 ${i<3?"lg:col-span-2":"lg:col-span-3"}`}><span className={`absolute inset-x-0 top-0 h-1 ${accent}`}/><Icon className="size-6 text-brand-petrol"/><h2 className="mt-6 text-xl">{title}</h2><p className="mt-3 flex-1 text-sm leading-relaxed text-brand-gray">{text}</p><Link to={to} className="mt-6 inline-flex items-center gap-2 text-sm font-semibold text-brand-petrol">{cta}<ArrowRight className="size-4 transition group-hover:translate-x-1"/></Link></article>)}</div></div></Section>
 <Section id="apoie" className="overflow-hidden bg-brand-soft"><div className="container-x grid gap-10 lg:grid-cols-[1fr_.95fr] lg:gap-16"><div><SectionTitle eyebrow="Apoie" title="Ajude a manter ideias em movimento."/><div className="space-y-4 leading-relaxed text-brand-gray"><p>Manter atividades culturais e comunitárias exige espaço, pessoas, materiais, equipamentos e continuidade.</p><p>Apoiar a Associação Maggu é contribuir para que ações de cultura, educação, leitura, cinema, esporte, memória e sustentabilidade continuem alcançando pessoas e território.</p><p>O apoio pode acontecer por meio de contribuição financeira, doação de materiais ou equipamentos, livros, prestação de serviços, parceria institucional ou patrocínio, conforme cada iniciativa.</p></div></div><ul className="grid grid-cols-2 gap-3">{support.map(({label,icon:Icon})=><li key={label} className="rounded-xl border border-brand-petrol/10 bg-background/70 p-4"><Icon className="size-4 text-brand-red"/><p className="mt-3 text-sm font-semibold leading-snug">{label}</p></li>)}</ul></div></Section>
 <Section id="parcerias" className="relative overflow-hidden bg-background"><ArcThick color="#FFB400" className="absolute -left-10 top-10 w-24 opacity-20" from={210} to={340}/><div className="container-x grid items-center gap-8 lg:grid-cols-[1fr_.8fr]"><div><SectionTitle eyebrow="Parcerias" title="Vamos construir juntos?"/><p className="leading-relaxed text-brand-gray">A Associação Maggu acredita em redes. Instituições públicas e privadas, organizações sociais, coletivos, empresas, artistas, educadores e profissionais podem construir conosco ações, formações, projetos, eventos, campanhas e outras formas de cooperação.</p><Button asChild className="mt-6 rounded-full bg-brand-petrol text-primary-foreground hover:bg-brand-red"><Link to="/contato">Propor parceria</Link></Button></div><div className="grid grid-cols-2 gap-3">{["Ações","Formações","Projetos","Cooperações"].map((item,i)=><div key={item} className="flex min-h-28 items-end rounded-2xl border border-brand-petrol/10 bg-brand-soft/60 p-4"><span className={`mr-3 size-2 rotate-45 ${i%2?"bg-brand-gold":"bg-brand-cyan"}`}/><p className="font-semibold">{item}</p></div>)}</div></div></Section>
 <Section id="colaboracao" className="overflow-hidden bg-brand-petrol text-primary-foreground"><div className="container-x grid items-center gap-6 md:grid-cols-[1fr_auto]"><div><p className="text-xs font-semibold uppercase tracking-[.22em] text-brand-gold">Colaboração</p><h2 className="mt-3 text-2xl text-primary-foreground md:text-3xl">Conhecimento também pode ser compartilhado.</h2><p className="mt-4 max-w-3xl leading-relaxed text-primary-foreground/80">Artistas, educadores, voluntários e outros profissionais podem colaborar com experiências, saberes e práticas em diferentes iniciativas da Associação.</p></div><Button asChild className="rounded-full bg-brand-cyan text-brand-petrol hover:bg-brand-gold"><Link to="/contato">Quero colaborar</Link></Button></div></Section>
 <Section className="overflow-hidden bg-background"><div className="container-x"><div className="mx-auto max-w-3xl rounded-2xl border border-brand-petrol/10 bg-brand-soft/55 p-7 text-center"><h2 className="text-2xl">Ainda não sabe qual caminho escolher?</h2><p className="mt-3 text-brand-gray">Fale com a Associação Maggu e conte como gostaria de participar.</p><Button asChild className="mt-5 rounded-full bg-brand-red text-primary-foreground hover:bg-brand-petrol"><Link to="/contato">Entre em contato</Link></Button></div></div></Section>
 <CompactFinalCTA title="Toda participação começa por um primeiro encontro." text="Conheça as atividades em andamento, formas de colaboração, apoio e parceria." primary={{label:"Ver Agenda",to:"/agenda"}} secondary={{label:"Entre em contato",to:"/contato"}} variant="home"/>
 </>}
