import { createFileRoute, Link } from "@tanstack/react-router";
import { Building2, Scale, ShieldCheck, Target, FileText, ArrowRight } from "lucide-react";
import { CompactFinalCTA } from "@/components/CompactFinalCTA";
import { HeroButton, PageHero, Section, SectionTitle } from "@/components/PageHero";
import { ArcThick, HatchedCircle, Triangle } from "@/components/Shapes";

export const Route = createFileRoute("/transparencia/governanca-integridade")({
  head: () => ({ meta: [
    { title: "Governança e Integridade | Associação Maggu" },
    { name: "description", content: "Conheça a estrutura de governança, os princípios e os canais de integridade da Associação Maggu." },
    { property: "og:title", content: "Governança e Integridade | Associação Maggu" },
    { property: "og:description", content: "Responsabilidades, decisões, fiscalização e integridade na Associação Maggu." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: Governanca,
});

const structures = [
  { title: "Assembleia Geral", text: "Instância de deliberação associativa conforme os instrumentos institucionais.", icon: Building2 },
  { title: "Diretoria", text: "Responsável pela condução administrativa e institucional da Associação.", icon: Target },
  { title: "Conselho Fiscal", text: "Estrutura de fiscalização prevista na governança da organização.", icon: Scale },
  { title: "Comissão ODS", text: "Instância consultiva e estratégica voltada à integração dos Objetivos de Desenvolvimento Sustentável às práticas, projetos e processos institucionais.", icon: ShieldCheck },
] as const;
const principles = ["Legalidade","Impessoalidade","Moralidade","Publicidade","Economicidade","Ética","Respeito à diversidade","Transparência","Responsabilidade"];
const practices = ["Responsabilidades definidas","Documentos acessíveis","Prestação de contas","Proteção de dados","Canais adequados de escuta"];
const expectedDocuments = ["Estatuto","Código de Ética/Conduta","Políticas institucionais","Documentos de governança","Atas publicáveis","Outros documentos oficiais"];

function Governanca() { return <>
  <PageHero eyebrow="Governança" title="Governança para cuidar do que construímos." subtitle="A Associação Maggu organiza responsabilidades, decisões, fiscalização e mecanismos de integridade para fortalecer sua atuação institucional com transparência e responsabilidade." image="https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1920&q=80" accent="gold" brush="#08B9E6" decoration="curve">
    <HeroButton to="#documentos" tone="gold">Ver documentos</HeroButton><HeroButton to="/canal-de-denuncias" tone="red">Acessar Canal de Denúncia</HeroButton>
  </PageHero>
  <Section className="overflow-hidden bg-background"><div className="container-x"><div className="mx-auto max-w-4xl text-center"><SectionTitle align="center" title="Estrutura, responsabilidade e transparência." /><div className="space-y-5 leading-relaxed text-brand-gray"><p>A Associação Maggu adota uma estrutura de governança formada por Assembleia Geral, Diretoria e Conselho Fiscal. Sua atuação observa princípios de legalidade, impessoalidade, moralidade, publicidade, economicidade, ética, respeito à diversidade, transparência e responsabilidade na gestão.</p><p>Integridade significa transformar esses princípios em práticas: documentos acessíveis, responsabilidades definidas, prestação de contas, proteção de dados, canais adequados de escuta e mecanismos para prevenir e encaminhar condutas incompatíveis com os valores institucionais.</p></div></div></div></Section>
  <Section className="relative overflow-hidden bg-brand-soft"><HatchedCircle size={150} color="#08B9E6" className="absolute -right-14 top-8 opacity-10" /><div className="container-x"><SectionTitle align="center" eyebrow="Estrutura" title="Como a Associação se organiza" />
    <div className="mx-auto max-w-4xl"><div className="grid items-center gap-3 md:grid-cols-[1fr_auto_1fr_auto_1fr]"><GovernanceNode label="Assembleia Geral" /><span className="rotate-90 text-2xl text-brand-cyan md:rotate-0">→</span><GovernanceNode label="Diretoria" /><span className="rotate-90 text-2xl text-brand-cyan md:rotate-0">→</span><GovernanceNode label="Conselho Fiscal" /></div><div className="mx-auto mt-4 max-w-md rounded-2xl border border-brand-gold/35 bg-background/75 p-4 text-center"><p className="text-xs font-semibold uppercase tracking-[0.18em] text-brand-red">Estrutura consultiva e estratégica</p><h3 className="mt-2">Comissão ODS</h3></div>
      <div className="mt-8 grid gap-3 sm:grid-cols-2"><div className="rounded-xl border border-brand-petrol/10 bg-background p-4"><p className="text-xs uppercase tracking-[0.16em] text-brand-gray">Diretor Geral</p><p className="mt-1 font-semibold text-brand-ink">Cristiano Alcides da Silva Paes</p></div><div className="rounded-xl border border-brand-petrol/10 bg-background p-4"><p className="text-xs uppercase tracking-[0.16em] text-brand-gray">Diretora Administrativo-Financeira</p><p className="mt-1 font-semibold text-brand-ink">Rafaela da Silva Leite</p></div></div>
    </div>
    <div className="mt-10 grid gap-4 sm:grid-cols-2 lg:grid-cols-4">{structures.map(({title,text,icon:Icon},i)=><article key={title} className="rounded-2xl border border-brand-petrol/10 bg-background/75 p-5 shadow-sm"><span className={`inline-flex size-9 items-center justify-center rounded-lg ${i%2 ? "bg-brand-gold/20" : "bg-brand-cyan/15"}`}><Icon className="size-4" /></span><h3 className="mt-4 text-lg">{title}</h3><p className="mt-2 text-sm leading-relaxed text-brand-gray">{text}</p></article>)}</div>
  </div></Section>
  <Section className="overflow-hidden bg-background"><div className="container-x"><SectionTitle eyebrow="Princípios" title="Princípios que orientam a gestão" /><ul className="grid grid-cols-2 gap-3 sm:grid-cols-3 lg:grid-cols-5">{principles.map((item,i)=><li key={item} className="flex min-h-20 items-center gap-3 rounded-xl border border-brand-petrol/10 bg-brand-soft/55 p-4 text-sm font-semibold"><span className={`size-2 shrink-0 rotate-45 ${i%3===0?"bg-brand-red":i%3===1?"bg-brand-gold":"bg-brand-cyan"}`} />{item}</li>)}</ul></div></Section>
  <Section className="overflow-hidden bg-brand-petrol text-primary-foreground"><div className="container-x"><SectionTitle invert align="center" title="Integridade também se constrói no cotidiano." /><ol className="relative grid gap-3 md:grid-cols-5"><span className="absolute left-[10%] right-[10%] top-5 hidden h-px bg-primary-foreground/20 md:block" />{practices.map((item,i)=><li key={item} className="relative flex items-center gap-3 rounded-xl border border-primary-foreground/15 bg-primary-foreground/[.07] p-4 backdrop-blur md:block md:pt-12 md:text-center"><span className="inline-flex size-8 shrink-0 items-center justify-center rounded-full bg-brand-gold text-xs font-bold text-brand-petrol md:absolute md:left-1/2 md:top-1 md:-translate-x-1/2">{i+1}</span><p className="text-sm font-semibold text-primary-foreground">{item}</p></li>)}</ol></div></Section>
  <Section id="documentos" className="overflow-hidden bg-background"><div className="container-x"><SectionTitle eyebrow="Documentos e políticas" title="Uma estrutura preparada para consulta pública." text="Os documentos de governança serão disponibilizados aqui quando os respectivos arquivos oficiais estiverem validados para publicação." /><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3">{expectedDocuments.map(item=><div key={item} className="flex items-center gap-3 rounded-xl border border-dashed border-brand-petrol/20 bg-brand-soft/40 p-4"><FileText className="size-4 text-brand-cyan" /><span className="text-sm font-semibold">{item}</span></div>)}</div></div></Section>
  <Section className="overflow-hidden bg-brand-soft"><div className="container-x"><SectionTitle align="center" eyebrow="Conexões" title="Políticas e canais institucionais" /><div className="mx-auto grid max-w-4xl gap-4 md:grid-cols-3">{[["ODS / Maggu 2030","/ods-maggu-2030"],["Canal de Denúncia e Relato Ético","/canal-de-denuncias"],["Política de Privacidade","/privacidade"]].map(([label,to])=><Link key={to} to={to} className="group flex min-h-28 items-end justify-between rounded-2xl border border-brand-petrol/10 bg-background p-5 font-semibold shadow-sm transition hover:-translate-y-1 hover:border-brand-cyan/40">{label}<ArrowRight className="size-4 transition group-hover:translate-x-1" /></Link>)}</div></div></Section>
  <CompactFinalCTA title="Transparência também é parte da governança." text="Acesse documentos, políticas e canais institucionais da Associação Maggu." primary={{label:"Ver Transparência",to:"/transparencia"}} secondary={{label:"Acessar Canal de Denúncia",to:"/canal-de-denuncias"}} variant="transparency" />
</> }
function GovernanceNode({label}:{label:string}) { return <div className="rounded-2xl border border-brand-petrol/10 bg-background px-5 py-5 text-center font-bold shadow-sm">{label}</div> }
