import { createFileRoute, Link } from "@tanstack/react-router";
import { Building2, Scale, ShieldCheck, Target, FileText, ArrowRight } from "lucide-react";
import { CompactFinalCTA } from "@/components/CompactFinalCTA";
import { HeroButton, PageHero, Section, SectionTitle } from "@/components/PageHero";
import { ArcThick, DiamondsCluster, HatchedCircle, QuarterCircle } from "@/components/Shapes";

export const Route = createFileRoute("/transparencia/governanca-integridade")({
  head: () => ({ meta: [
    { title: "Governança e Integridade | Associação Maggu" },
    { name: "description", content: "Conheça a estrutura de governança, os princípios e os canais de integridade da Associação Maggu." },
    { property: "og:title", content: "Governança e Integridade | Associação Maggu" },
    { property: "og:description", content: "Responsabilidades, decisões, fiscalização e integridade na Associação Maggu." },
    { property: "og:type", content: "website" }, { name: "twitter:card", content: "summary_large_image" },
  ]}), component: Governanca,
});

const structures = [
  { title: "Assembleia Geral", text: "Instância de deliberação associativa conforme os instrumentos institucionais.", icon: Building2 },
  { title: "Diretoria", text: "Responsável pela condução administrativa e institucional da Associação.", icon: Target },
  { title: "Conselho Fiscal", text: "Estrutura de fiscalização prevista na governança da organização.", icon: Scale },
  { title: "Comissão ODS", text: "Instância consultiva e estratégica voltada à integração dos Objetivos de Desenvolvimento Sustentável às práticas, projetos e processos institucionais.", icon: ShieldCheck },
] as const;
const principles = ["Legalidade","Impessoalidade","Moralidade","Publicidade","Economicidade","Ética","Respeito à diversidade","Transparência","Responsabilidade"];
const practices = ["Responsabilidades definidas","Documentos acessíveis","Prestação de contas","Proteção de dados","Canais adequados de escuta"];
const expectedDocuments = ["Estatuto","Código de Ética/Conduta","Políticas institucionais","Documentos de governança","Atas publicáveis","Outros documentos oficiais"];

function Governanca() { return <>
  <PageHero eyebrow="Governança" title="Governança para cuidar do que construímos." subtitle="A Associação Maggu organiza responsabilidades, decisões, fiscalização e mecanismos de integridade para fortalecer sua atuação institucional com transparência e responsabilidade." image="https://images.unsplash.com/photo-1524178232363-1fb2b075b655?auto=format&fit=crop&w=1920&q=80" accent="gold" brush="#08B9E6" decoration="curve">
    <HeroButton to="#documentos" tone="gold">Ver documentos</HeroButton><HeroButton to="/canal-de-denuncias" tone="red">Acessar Canal de Denúncia</HeroButton>
  </PageHero>
  <Section className="overflow-hidden bg-background"><ArcThick color="#FFB400" className="pointer-events-none absolute -left-12 top-9 w-24 opacity-[0.12]" from={210} to={335} /><DiamondsCluster color="#08B9E6" className="pointer-events-none absolute -right-2 bottom-8 hidden opacity-[0.12] md:block" size={58} /><div className="container-x"><div className="relative mx-auto max-w-4xl text-center"><span className="pointer-events-none absolute -left-5 top-1/2 hidden h-px w-10 bg-brand-red/50 lg:block" aria-hidden="true" /><span className="pointer-events-none absolute -right-4 top-3 hidden size-3 rotate-45 bg-brand-gold lg:block" aria-hidden="true" /><SectionTitle align="center" title="Estrutura, responsabilidade e transparência." /><div className="space-y-5 leading-relaxed text-brand-gray"><p>A Associação Maggu adota uma estrutura de governança formada por Assembleia Geral, Diretoria e Conselho Fiscal. Sua atuação observa princípios de legalidade, impessoalidade, moralidade, publicidade, economicidade, ética, respeito à diversidade, transparência e responsabilidade na gestão.</p><p>Integridade significa transformar esses princípios em práticas: documentos acessíveis, responsabilidades definidas, prestação de contas, proteção de dados, canais adequados de escuta e mecanismos para prevenir e encaminhar condutas incompatíveis com os valores institucionais.</p></div></div></div></Section>
  <Section className="relative overflow-hidden bg-brand-soft"><HatchedCircle size={150} color="#08B9E6" className="absolute -right-14 top-8 opacity-10" /><div className="container-x"><SectionTitle align="center" eyebrow="Estrutura" title="Como a Associação se organiza" />
    <div className="mx-auto max-w-4xl"><div className="grid items-center gap-2 md:grid-cols-[1fr_auto_1fr_auto_1fr]"><GovernanceNode label="Assembleia Geral" index="01" tone="red" /><span className="rotate-90 text-xl text-brand-cyan md:rotate-0">→</span><GovernanceNode label="Diretoria" index="02" tone="gold" /><span className="rotate-90 text-xl text-brand-cyan md:rotate-0">→</span><GovernanceNode label="Conselho Fiscal" index="03" tone="cyan" /></div><div className="relative mx-auto mt-4 max-w-md overflow-hidden rounded-[12px] border border-brand-gold/30 bg-background p-4 text-center shadow-[0_14px_30px_-28px_rgba(0,56,76,0.65)]"><span className="absolute inset-y-0 left-0 w-1 bg-brand-gold" aria-hidden="true" /><p className="text-xs font-semibold uppercase tracking-[0.18em] text-brand-red">Estrutura consultiva e estratégica</p><h3 className="mt-2">Comissão ODS</h3></div>
      <div className="mt-7 grid gap-3 sm:grid-cols-2"><div className="relative overflow-hidden rounded-[12px] border border-brand-petrol/10 bg-background p-4 shadow-[0_12px_28px_-27px_rgba(0,56,76,0.7)]"><span className="absolute right-4 top-4 size-2 rotate-45 bg-brand-red" aria-hidden="true" /><p className="text-xs uppercase tracking-[0.16em] text-brand-gray">Diretor Geral</p><p className="mt-1 font-semibold text-brand-ink">Cristiano Alcides da Silva Paes</p></div><div className="relative overflow-hidden rounded-[12px] border border-brand-petrol/10 bg-background p-4 shadow-[0_12px_28px_-27px_rgba(0,56,76,0.7)]"><span className="absolute right-0 top-0 size-10 rounded-bl-full bg-brand-cyan/10" aria-hidden="true" /><p className="text-xs uppercase tracking-[0.16em] text-brand-gray">Diretora Administrativo-Financeira</p><p className="mt-1 font-semibold text-brand-ink">Rafaela da Silva Leite</p></div></div>
    </div>
    <div className="mt-9 grid gap-3 sm:grid-cols-2 lg:grid-cols-4">{structures.map(({title,text,icon:Icon},i)=><article key={title} className="group relative min-h-52 overflow-hidden rounded-[12px] border border-brand-petrol/10 bg-background/85 p-5 shadow-[0_16px_34px_-30px_rgba(0,56,76,0.7)] transition hover:-translate-y-1 hover:border-brand-cyan/30"><span className={`absolute inset-x-0 top-0 h-0.5 ${i%3===0?"bg-brand-red":i%3===1?"bg-brand-gold":"bg-brand-cyan"}`} aria-hidden="true" />{i%2===0?<span className="absolute -right-5 -top-5 size-16 rounded-full bg-brand-cyan/8" aria-hidden="true" />:<span className="absolute right-5 top-5 size-2 rotate-45 bg-brand-gold" aria-hidden="true" />}<span className={`inline-flex size-10 items-center justify-center rounded-full ${i%2 ? "bg-brand-gold/15" : "bg-brand-cyan/12"}`}><Icon className="size-4 text-brand-petrol" /></span><h3 className="mt-4 text-lg">{title}</h3><p className="mt-2 text-[13px] leading-relaxed text-brand-gray">{text}</p></article>)}</div>
  </div></Section>
  <Section className="overflow-hidden bg-background"><QuarterCircle corner="br" color="#FFB400" className="pointer-events-none absolute -left-5 bottom-8 w-12 opacity-[0.12]" /><HatchedCircle size={96} color="#08B9E6" className="pointer-events-none absolute -right-8 top-10 opacity-[0.08]" /><div className="container-x"><SectionTitle eyebrow="Princípios" title="Princípios que orientam a gestão" /><ul className="grid grid-cols-2 gap-2.5 sm:grid-cols-3 lg:grid-cols-5">{principles.map((item,i)=><li key={item} className={`group relative flex min-h-24 flex-col justify-between overflow-hidden rounded-[11px] border border-brand-petrol/10 p-4 text-sm font-semibold shadow-[0_12px_26px_-28px_rgba(0,56,76,0.7)] transition hover:-translate-y-0.5 ${i%4===0?"bg-brand-soft":i%4===1?"bg-brand-gold/10":"bg-background"}`}><span className={`h-0.5 w-7 ${i%3===0?"bg-brand-red":i%3===1?"bg-brand-gold":"bg-brand-cyan"}`} /><span>{item}</span>{i%3===2&&<span className="absolute -right-3 -top-3 size-8 rounded-full bg-brand-cyan/8" aria-hidden="true" />}</li>)}</ul></div></Section>
  <Section className="overflow-hidden bg-brand-soft"><ArcThick color="#08B9E6" className="pointer-events-none absolute -right-12 bottom-2 w-24 opacity-[0.1]" from={205} to={325} /><div className="container-x"><SectionTitle align="center" title="Integridade também se constrói no cotidiano." /><ol className="relative mx-auto grid max-w-5xl gap-3 md:grid-cols-5"><span className="absolute left-[10%] right-[10%] top-6 hidden h-px bg-brand-cyan/30 md:block" />{practices.map((item,i)=><li key={item} className="group relative flex min-h-24 items-center gap-3 overflow-hidden rounded-[12px] border border-brand-petrol/10 bg-background/85 p-4 shadow-[0_14px_30px_-28px_rgba(0,56,76,0.65)] transition hover:-translate-y-0.5 md:block md:min-h-32 md:pt-14 md:text-center"><span className={`inline-flex size-9 shrink-0 items-center justify-center rounded-full text-xs font-bold text-brand-petrol md:absolute md:left-1/2 md:top-1.5 md:-translate-x-1/2 ${i%3===0?"bg-brand-gold":i%3===1?"bg-brand-cyan/30":"bg-brand-red/15"}`}>{i+1}</span><p className="text-sm font-semibold text-brand-ink">{item}</p><span className={`absolute inset-x-0 bottom-0 h-0.5 ${i%2?"bg-brand-cyan":"bg-brand-gold"}`} aria-hidden="true" /></li>)}</ol></div></Section>
  <Section id="documentos" className="overflow-hidden bg-background"><div className="container-x"><div className="mx-auto max-w-4xl"><SectionTitle eyebrow="Documentos e políticas" title="Uma estrutura preparada para consulta pública." text="Os documentos de governança serão disponibilizados aqui quando os respectivos arquivos oficiais estiverem validados para publicação." /><div className="grid grid-cols-2 gap-3 md:grid-cols-3">{expectedDocuments.map((item,i)=><div key={item} className="group relative flex min-h-28 flex-col justify-between overflow-hidden rounded-[12px] border border-brand-petrol/10 bg-brand-soft/40 p-4 shadow-[0_12px_28px_-28px_rgba(0,56,76,0.65)] transition hover:border-brand-cyan/30 hover:bg-brand-soft/65"><span className={`inline-flex size-9 items-center justify-center rounded-full ${i%2?"bg-brand-gold/15":"bg-brand-cyan/12"}`}><FileText className="size-4 text-brand-petrol" /></span><span className="mt-4 text-sm font-semibold leading-snug">{item}</span>{i%3===0&&<span className="absolute right-4 top-4 size-2 rotate-45 bg-brand-red" aria-hidden="true" />}</div>)}</div></div></div></Section>
  <Section className="overflow-hidden bg-brand-soft"><HatchedCircle size={90} color="#00384C" className="pointer-events-none absolute -left-8 bottom-8 opacity-[0.06]" /><div className="container-x"><SectionTitle align="center" eyebrow="Conexões" title="Políticas e canais institucionais" /><div className="mx-auto grid max-w-4xl gap-3 md:grid-cols-3">{[["ODS / Maggu 2030","/ods-maggu-2030"],["Canal de Denúncia e Relato Ético","/canal-de-denuncias"],["Política de Privacidade","/privacidade"]].map(([label,to],i)=><Link key={to} to={to} className="group relative flex min-h-36 flex-col justify-between overflow-hidden rounded-[12px] border border-brand-petrol/10 bg-background p-5 font-semibold shadow-[0_16px_34px_-30px_rgba(0,56,76,0.7)] transition hover:-translate-y-1 hover:border-brand-cyan/40"><span className={`h-0.5 w-9 ${i===0?"bg-brand-gold":i===1?"bg-brand-red":"bg-brand-cyan"}`} aria-hidden="true" /><span className="max-w-[13rem] leading-snug">{label}</span><ArrowRight className="absolute bottom-5 right-5 size-4 text-brand-petrol transition group-hover:translate-x-1" />{i===0&&<span className="absolute -right-5 -top-5 size-16 rounded-full border-[8px] border-brand-gold/12" aria-hidden="true" />}{i===1&&<span className="absolute right-5 top-5 size-2 rotate-45 bg-brand-red/70" aria-hidden="true" />}</Link>)}</div></div></Section>
  <CompactFinalCTA title="Transparência também é parte da governança." text="Acesse documentos, políticas e canais institucionais da Associação Maggu." primary={{label:"Ver Transparência",to:"/transparencia"}} secondary={{label:"Acessar Canal de Denúncia",to:"/canal-de-denuncias"}} variant="transparency" />
</> }
function GovernanceNode({label,index,tone}:{label:string;index:string;tone:"red"|"gold"|"cyan"}) { const toneClass={red:"bg-brand-red",gold:"bg-brand-gold",cyan:"bg-brand-cyan"}[tone]; return <div className="relative overflow-hidden rounded-[12px] border border-brand-petrol/10 bg-background px-5 py-5 text-center font-bold shadow-[0_14px_30px_-28px_rgba(0,56,76,0.7)]"><span className={`absolute inset-y-0 left-0 w-1 ${toneClass}`} aria-hidden="true" /><span className="mb-2 block text-[10px] font-semibold tracking-[0.18em] text-brand-gray/60">{index}</span>{label}</div> }
