/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as TermosDeUsoRouteImport } from './routes/termos-de-uso'
import { Route as PrivacidadeRouteImport } from './routes/privacidade'
import { Route as OdsMaggu2030RouteImport } from './routes/ods-maggu-2030'
import { Route as ImprensaRouteImport } from './routes/imprensa'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as EcossistemaRouteImport } from './routes/ecossistema'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as CanalDeDenunciasRouteImport } from './routes/canal-de-denuncias'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TransparenciaIndexRouteImport } from './routes/transparencia/index'
import { Route as QuemSomosIndexRouteImport } from './routes/quem-somos/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos/index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias/index'
import { Route as GaleriaIndexRouteImport } from './routes/galeria/index'
import { Route as AgendaIndexRouteImport } from './routes/agenda/index'
import { Route as QuemSomosTerritorioRouteImport } from './routes/quem-somos/territorio'
import { Route as ProjetosSlugRouteImport } from './routes/projetos/$slug'
import { Route as NoticiasSlugRouteImport } from './routes/noticias/$slug'
import { Route as GaleriaSlugRouteImport } from './routes/galeria/$slug'
import { Route as AgendaSlugRouteImport } from './routes/agenda/$slug'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const TermosDeUsoRoute = TermosDeUsoRouteImport.update({
  id: '/termos-de-uso',
  path: '/termos-de-uso',
  getParentRoute: () => rootRouteImport,
} as any)
const PrivacidadeRoute = PrivacidadeRouteImport.update({
  id: '/privacidade',
  path: '/privacidade',
  getParentRoute: () => rootRouteImport,
} as any)
const OdsMaggu2030Route = OdsMaggu2030RouteImport.update({
  id: '/ods-maggu-2030',
  path: '/ods-maggu-2030',
  getParentRoute: () => rootRouteImport,
} as any)
const ImprensaRoute = ImprensaRouteImport.update({
  id: '/imprensa',
  path: '/imprensa',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const EcossistemaRoute = EcossistemaRouteImport.update({
  id: '/ecossistema',
  path: '/ecossistema',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const CanalDeDenunciasRoute = CanalDeDenunciasRouteImport.update({
  id: '/canal-de-denuncias',
  path: '/canal-de-denuncias',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TransparenciaIndexRoute = TransparenciaIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => TransparenciaRoute,
} as any)
const QuemSomosIndexRoute = QuemSomosIndexRouteImport.update({
  id: '/quem-somos/',
  path: '/quem-somos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaIndexRoute = GaleriaIndexRouteImport.update({
  id: '/galeria/',
  path: '/galeria/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaIndexRoute = AgendaIndexRouteImport.update({
  id: '/agenda/',
  path: '/agenda/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosTerritorioRoute = QuemSomosTerritorioRouteImport.update({
  id: '/quem-somos/territorio',
  path: '/quem-somos/territorio',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/projetos/$slug',
  path: '/projetos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaSlugRoute = GaleriaSlugRouteImport.update({
  id: '/galeria/$slug',
  path: '/galeria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const AgendaSlugRoute = AgendaSlugRouteImport.update({
  id: '/agenda/$slug',
  path: '/agenda/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/canal-de-denuncias': typeof CanalDeDenunciasRoute
  '/contato': typeof ContatoRoute
  '/ecossistema': typeof EcossistemaRoute
  '/equipe': typeof EquipeRoute
  '/imprensa': typeof ImprensaRoute
  '/ods-maggu-2030': typeof OdsMaggu2030Route
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/transparencia': typeof TransparenciaRouteWithChildren
  '/agenda/$slug': typeof AgendaSlugRoute
  '/galeria/$slug': typeof GaleriaSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/quem-somos/territorio': typeof QuemSomosTerritorioRoute
  '/agenda/': typeof AgendaIndexRoute
  '/galeria/': typeof GaleriaIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/quem-somos/': typeof QuemSomosIndexRoute
  '/transparencia/': typeof TransparenciaIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/canal-de-denuncias': typeof CanalDeDenunciasRoute
  '/contato': typeof ContatoRoute
  '/ecossistema': typeof EcossistemaRoute
  '/equipe': typeof EquipeRoute
  '/imprensa': typeof ImprensaRoute
  '/ods-maggu-2030': typeof OdsMaggu2030Route
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/agenda/$slug': typeof AgendaSlugRoute
  '/galeria/$slug': typeof GaleriaSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/quem-somos/territorio': typeof QuemSomosTerritorioRoute
  '/agenda': typeof AgendaIndexRoute
  '/galeria': typeof GaleriaIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/projetos': typeof ProjetosIndexRoute
  '/quem-somos': typeof QuemSomosIndexRoute
  '/transparencia': typeof TransparenciaIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/canal-de-denuncias': typeof CanalDeDenunciasRoute
  '/contato': typeof ContatoRoute
  '/ecossistema': typeof EcossistemaRoute
  '/equipe': typeof EquipeRoute
  '/imprensa': typeof ImprensaRoute
  '/ods-maggu-2030': typeof OdsMaggu2030Route
  '/privacidade': typeof PrivacidadeRoute
  '/termos-de-uso': typeof TermosDeUsoRoute
  '/transparencia': typeof TransparenciaRouteWithChildren
  '/agenda/$slug': typeof AgendaSlugRoute
  '/galeria/$slug': typeof GaleriaSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/quem-somos/territorio': typeof QuemSomosTerritorioRoute
  '/agenda/': typeof AgendaIndexRoute
  '/galeria/': typeof GaleriaIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/quem-somos/': typeof QuemSomosIndexRoute
  '/transparencia/': typeof TransparenciaIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/canal-de-denuncias'
    | '/contato'
    | '/ecossistema'
    | '/equipe'
    | '/imprensa'
    | '/ods-maggu-2030'
    | '/privacidade'
    | '/termos-de-uso'
    | '/transparencia'
    | '/agenda/$slug'
    | '/galeria/$slug'
    | '/noticias/$slug'
    | '/projetos/$slug'
    | '/quem-somos/territorio'
    | '/agenda/'
    | '/galeria/'
    | '/noticias/'
    | '/projetos/'
    | '/quem-somos/'
    | '/transparencia/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/canal-de-denuncias'
    | '/contato'
    | '/ecossistema'
    | '/equipe'
    | '/imprensa'
    | '/ods-maggu-2030'
    | '/privacidade'
    | '/termos-de-uso'
    | '/agenda/$slug'
    | '/galeria/$slug'
    | '/noticias/$slug'
    | '/projetos/$slug'
    | '/quem-somos/territorio'
    | '/agenda'
    | '/galeria'
    | '/noticias'
    | '/projetos'
    | '/quem-somos'
    | '/transparencia'
  id:
    | '__root__'
    | '/'
    | '/canal-de-denuncias'
    | '/contato'
    | '/ecossistema'
    | '/equipe'
    | '/imprensa'
    | '/ods-maggu-2030'
    | '/privacidade'
    | '/termos-de-uso'
    | '/transparencia'
    | '/agenda/$slug'
    | '/galeria/$slug'
    | '/noticias/$slug'
    | '/projetos/$slug'
    | '/quem-somos/territorio'
    | '/agenda/'
    | '/galeria/'
    | '/noticias/'
    | '/projetos/'
    | '/quem-somos/'
    | '/transparencia/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CanalDeDenunciasRoute: typeof CanalDeDenunciasRoute
  ContatoRoute: typeof ContatoRoute
  EcossistemaRoute: typeof EcossistemaRoute
  EquipeRoute: typeof EquipeRoute
  ImprensaRoute: typeof ImprensaRoute
  OdsMaggu2030Route: typeof OdsMaggu2030Route
  PrivacidadeRoute: typeof PrivacidadeRoute
  TermosDeUsoRoute: typeof TermosDeUsoRoute
  TransparenciaRoute: typeof TransparenciaRouteWithChildren
  AgendaSlugRoute: typeof AgendaSlugRoute
  GaleriaSlugRoute: typeof GaleriaSlugRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  QuemSomosTerritorioRoute: typeof QuemSomosTerritorioRoute
  AgendaIndexRoute: typeof AgendaIndexRoute
  GaleriaIndexRoute: typeof GaleriaIndexRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
  QuemSomosIndexRoute: typeof QuemSomosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/termos-de-uso': {
      id: '/termos-de-uso'
      path: '/termos-de-uso'
      fullPath: '/termos-de-uso'
      preLoaderRoute: typeof TermosDeUsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/privacidade': {
      id: '/privacidade'
      path: '/privacidade'
      fullPath: '/privacidade'
      preLoaderRoute: typeof PrivacidadeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ods-maggu-2030': {
      id: '/ods-maggu-2030'
      path: '/ods-maggu-2030'
      fullPath: '/ods-maggu-2030'
      preLoaderRoute: typeof OdsMaggu2030RouteImport
      parentRoute: typeof rootRouteImport
    }
    '/imprensa': {
      id: '/imprensa'
      path: '/imprensa'
      fullPath: '/imprensa'
      preLoaderRoute: typeof ImprensaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ecossistema': {
      id: '/ecossistema'
      path: '/ecossistema'
      fullPath: '/ecossistema'
      preLoaderRoute: typeof EcossistemaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/canal-de-denuncias': {
      id: '/canal-de-denuncias'
      path: '/canal-de-denuncias'
      fullPath: '/canal-de-denuncias'
      preLoaderRoute: typeof CanalDeDenunciasRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/transparencia/': {
      id: '/transparencia/'
      path: '/'
      fullPath: '/transparencia/'
      preLoaderRoute: typeof TransparenciaIndexRouteImport
      parentRoute: typeof TransparenciaRoute
    }
    '/quem-somos/': {
      id: '/quem-somos/'
      path: '/quem-somos'
      fullPath: '/quem-somos/'
      preLoaderRoute: typeof QuemSomosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria/': {
      id: '/galeria/'
      path: '/galeria'
      fullPath: '/galeria/'
      preLoaderRoute: typeof GaleriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/': {
      id: '/agenda/'
      path: '/agenda'
      fullPath: '/agenda/'
      preLoaderRoute: typeof AgendaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos/territorio': {
      id: '/quem-somos/territorio'
      path: '/quem-somos/territorio'
      fullPath: '/quem-somos/territorio'
      preLoaderRoute: typeof QuemSomosTerritorioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/projetos/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria/$slug': {
      id: '/galeria/$slug'
      path: '/galeria/$slug'
      fullPath: '/galeria/$slug'
      preLoaderRoute: typeof GaleriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agenda/$slug': {
      id: '/agenda/$slug'
      path: '/agenda/$slug'
      fullPath: '/agenda/$slug'
      preLoaderRoute: typeof AgendaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface TransparenciaRouteChildren {
  TransparenciaIndexRoute: typeof TransparenciaIndexRoute
}

const TransparenciaRouteChildren: TransparenciaRouteChildren = {
  TransparenciaIndexRoute: TransparenciaIndexRoute,
}

const TransparenciaRouteWithChildren = TransparenciaRoute._addFileChildren(
  TransparenciaRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CanalDeDenunciasRoute: CanalDeDenunciasRoute,
  ContatoRoute: ContatoRoute,
  EcossistemaRoute: EcossistemaRoute,
  EquipeRoute: EquipeRoute,
  ImprensaRoute: ImprensaRoute,
  OdsMaggu2030Route: OdsMaggu2030Route,
  PrivacidadeRoute: PrivacidadeRoute,
  TermosDeUsoRoute: TermosDeUsoRoute,
  TransparenciaRoute: TransparenciaRouteWithChildren,
  AgendaSlugRoute: AgendaSlugRoute,
  GaleriaSlugRoute: GaleriaSlugRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  ProjetosSlugRoute: ProjetosSlugRoute,
  QuemSomosTerritorioRoute: QuemSomosTerritorioRoute,
  AgendaIndexRoute: AgendaIndexRoute,
  GaleriaIndexRoute: GaleriaIndexRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
  QuemSomosIndexRoute: QuemSomosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
