/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TransparenciaRouteImport } from './routes/transparencia'
import { Route as EquipeRouteImport } from './routes/equipe'
import { Route as ContatoRouteImport } from './routes/contato'
import { Route as IndexRouteImport } from './routes/index'
import { Route as QuemSomosIndexRouteImport } from './routes/quem-somos/index'
import { Route as ProjetosIndexRouteImport } from './routes/projetos/index'
import { Route as NoticiasIndexRouteImport } from './routes/noticias/index'
import { Route as GaleriaIndexRouteImport } from './routes/galeria/index'
import { Route as ProjetosSlugRouteImport } from './routes/projetos/$slug'
import { Route as NoticiasSlugRouteImport } from './routes/noticias/$slug'
import { Route as GaleriaSlugRouteImport } from './routes/galeria/$slug'

const TransparenciaRoute = TransparenciaRouteImport.update({
  id: '/transparencia',
  path: '/transparencia',
  getParentRoute: () => rootRouteImport,
} as any)
const EquipeRoute = EquipeRouteImport.update({
  id: '/equipe',
  path: '/equipe',
  getParentRoute: () => rootRouteImport,
} as any)
const ContatoRoute = ContatoRouteImport.update({
  id: '/contato',
  path: '/contato',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const QuemSomosIndexRoute = QuemSomosIndexRouteImport.update({
  id: '/quem-somos/',
  path: '/quem-somos/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosIndexRoute = ProjetosIndexRouteImport.update({
  id: '/projetos/',
  path: '/projetos/',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasIndexRoute = NoticiasIndexRouteImport.update({
  id: '/noticias/',
  path: '/noticias/',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaIndexRoute = GaleriaIndexRouteImport.update({
  id: '/galeria/',
  path: '/galeria/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProjetosSlugRoute = ProjetosSlugRouteImport.update({
  id: '/projetos/$slug',
  path: '/projetos/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const NoticiasSlugRoute = NoticiasSlugRouteImport.update({
  id: '/noticias/$slug',
  path: '/noticias/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const GaleriaSlugRoute = GaleriaSlugRouteImport.update({
  id: '/galeria/$slug',
  path: '/galeria/$slug',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/transparencia': typeof TransparenciaRoute
  '/galeria/$slug': typeof GaleriaSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/galeria/': typeof GaleriaIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/quem-somos/': typeof QuemSomosIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/transparencia': typeof TransparenciaRoute
  '/galeria/$slug': typeof GaleriaSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/galeria': typeof GaleriaIndexRoute
  '/noticias': typeof NoticiasIndexRoute
  '/projetos': typeof ProjetosIndexRoute
  '/quem-somos': typeof QuemSomosIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/contato': typeof ContatoRoute
  '/equipe': typeof EquipeRoute
  '/transparencia': typeof TransparenciaRoute
  '/galeria/$slug': typeof GaleriaSlugRoute
  '/noticias/$slug': typeof NoticiasSlugRoute
  '/projetos/$slug': typeof ProjetosSlugRoute
  '/galeria/': typeof GaleriaIndexRoute
  '/noticias/': typeof NoticiasIndexRoute
  '/projetos/': typeof ProjetosIndexRoute
  '/quem-somos/': typeof QuemSomosIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/contato'
    | '/equipe'
    | '/transparencia'
    | '/galeria/$slug'
    | '/noticias/$slug'
    | '/projetos/$slug'
    | '/galeria/'
    | '/noticias/'
    | '/projetos/'
    | '/quem-somos/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/contato'
    | '/equipe'
    | '/transparencia'
    | '/galeria/$slug'
    | '/noticias/$slug'
    | '/projetos/$slug'
    | '/galeria'
    | '/noticias'
    | '/projetos'
    | '/quem-somos'
  id:
    | '__root__'
    | '/'
    | '/contato'
    | '/equipe'
    | '/transparencia'
    | '/galeria/$slug'
    | '/noticias/$slug'
    | '/projetos/$slug'
    | '/galeria/'
    | '/noticias/'
    | '/projetos/'
    | '/quem-somos/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ContatoRoute: typeof ContatoRoute
  EquipeRoute: typeof EquipeRoute
  TransparenciaRoute: typeof TransparenciaRoute
  GaleriaSlugRoute: typeof GaleriaSlugRoute
  NoticiasSlugRoute: typeof NoticiasSlugRoute
  ProjetosSlugRoute: typeof ProjetosSlugRoute
  GaleriaIndexRoute: typeof GaleriaIndexRoute
  NoticiasIndexRoute: typeof NoticiasIndexRoute
  ProjetosIndexRoute: typeof ProjetosIndexRoute
  QuemSomosIndexRoute: typeof QuemSomosIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/transparencia': {
      id: '/transparencia'
      path: '/transparencia'
      fullPath: '/transparencia'
      preLoaderRoute: typeof TransparenciaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/equipe': {
      id: '/equipe'
      path: '/equipe'
      fullPath: '/equipe'
      preLoaderRoute: typeof EquipeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contato': {
      id: '/contato'
      path: '/contato'
      fullPath: '/contato'
      preLoaderRoute: typeof ContatoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quem-somos/': {
      id: '/quem-somos/'
      path: '/quem-somos'
      fullPath: '/quem-somos/'
      preLoaderRoute: typeof QuemSomosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/': {
      id: '/projetos/'
      path: '/projetos'
      fullPath: '/projetos/'
      preLoaderRoute: typeof ProjetosIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/': {
      id: '/noticias/'
      path: '/noticias'
      fullPath: '/noticias/'
      preLoaderRoute: typeof NoticiasIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria/': {
      id: '/galeria/'
      path: '/galeria'
      fullPath: '/galeria/'
      preLoaderRoute: typeof GaleriaIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/projetos/$slug': {
      id: '/projetos/$slug'
      path: '/projetos/$slug'
      fullPath: '/projetos/$slug'
      preLoaderRoute: typeof ProjetosSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/noticias/$slug': {
      id: '/noticias/$slug'
      path: '/noticias/$slug'
      fullPath: '/noticias/$slug'
      preLoaderRoute: typeof NoticiasSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/galeria/$slug': {
      id: '/galeria/$slug'
      path: '/galeria/$slug'
      fullPath: '/galeria/$slug'
      preLoaderRoute: typeof GaleriaSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ContatoRoute: ContatoRoute,
  EquipeRoute: EquipeRoute,
  TransparenciaRoute: TransparenciaRoute,
  GaleriaSlugRoute: GaleriaSlugRoute,
  NoticiasSlugRoute: NoticiasSlugRoute,
  ProjetosSlugRoute: ProjetosSlugRoute,
  GaleriaIndexRoute: GaleriaIndexRoute,
  NoticiasIndexRoute: NoticiasIndexRoute,
  ProjetosIndexRoute: ProjetosIndexRoute,
  QuemSomosIndexRoute: QuemSomosIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
